services:
  # Landing Page - furrycore.com.br
  landing:
    build:
      context: .
      dockerfile: ./apps/landing/Dockerfile
    container_name: furry_landing
    restart: always
    expose:
      - "20000"
    networks:
      - furry_net

  # Rede Social - pawsteps.social
  pawsteps:
    build:
      context: .
      dockerfile: ./apps/pawsteps/Dockerfile
    container_name: furry_pawsteps
    restart: always
    expose:
      - "20001"
    volumes:
      - ./apps/pawsteps/database:/app/database
      - ./apps/pawsteps/static/uploads:/app/static/uploads
    networks:
      - furry_net

  # Portal CGRF - cgrf.com.br
  cgrf:
    build:
      context: .
      dockerfile: ./apps/cgrf/Dockerfile
    container_name: furry_cgrf
    restart: always
    expose:
      - "20002"
    volumes:
      - ./apps/cgrf/database:/app/database
      - ./apps/pawsteps/database:/app/shared_data/pawsteps
      - ./apps/shop/database:/app/shared_data/shop
      - ./shared:/app/shared
    networks:
      - furry_net

  # Loja - furrycore.com.br/shop
  shop:
    build:
      context: .
      dockerfile: ./apps/shop/Dockerfile
    container_name: furry_shop
    restart: always
    expose:
      - "20003"
    networks:
      - furry_net

  # Proxy Reverso (Nginx)
  nginx:
    image: nginx:alpine
    container_name: furry_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - landing
      - pawsteps
      - cgrf
      - shop
    networks:
      - furry_net

  # Zabbix Agent para Monitoramento
  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: furry_zabbix_agent
    restart: always
    ports:
      - "10055:10050"
    environment:
      - ZBX_SERVER_HOST=187.77.233.230
      - ZBX_HOSTNAME=SRV-AUTOMACAO
    networks:
      - furry_net

  # Admin Dashboard - Central de Controle
  admin-dash:
    build:
      context: .
      dockerfile: ./apps/admin-dash/Dockerfile
    container_name: furry_admin
    restart: always
    ports:
      - "29999:29999"
    volumes:
      - ./apps/admin-dash/database:/app/database
      - ./nginx_logs:/app/shared_logs # Logs do Nginx para monitoramento
      - ./apps/cgrf/database:/app/shared_data/cgrf # DB CGRF
      - ./apps/pawsteps/database:/app/shared_data/pawsteps # DB PawSteps
      - ./apps/shop/database:/app/shared_data/shop # DB Shop
    env_file: .env
    networks:
      - furry_net
    depends_on:
      - nginx

networks:
  furry_net:
    driver: bridge
