events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    # Proteção DDoS básica (Rate Limiting)
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=addr:10m;

    server {
        listen 80;
        server_name furrycore.com.br;

        location / {
            limit_req zone=mylimit burst=20 nodelay;
            proxy_pass http://landing:20000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /shop {
            proxy_pass http://shop:20003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name pawsteps.social;

        location / {
            limit_req zone=mylimit burst=20 nodelay;
            proxy_pass http://pawsteps:20001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name cgrf.com.br;

        location / {
            limit_req zone=mylimit burst=10 nodelay;
            proxy_pass http://cgrf:20002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
